// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chat_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ChatModel _$ChatModelFromJson(Map<String, dynamic> json) => ChatModel(
      roomId: json['room_id'] as int,
      messageId: json['message_id'] as int,
      messageReaction: json['message_reaction'] as List<dynamic>,
      fromUserId: json['from_user_id'] as int,
      fromEmpId: json['from_emp_id'] as int,
      fromUsername: json['from_username'] as String,
      fromUsernamePhoto: json['from_username_photo'] as String,
      toUserId: json['to_user_id'] as int,
      toUsername: json['to_username'] as String,
      toUsernamePhoto: json['to_username_photo'] as String,
      messageType: json['message_type'] as String?,
      messageText: json['message_text'] as String?,
      messageAttachmentName: json['message_attachment_name'] as String?,
      messageAttachment: json['message_attachment'] as String?,
      messageFileDuration: json['message_file_duration'] as int?,
      messageAttachmentThumbnail:
          json['message_attachment_thumbnail'] as String?,
      messageStatus: json['message_status'] as String?,
      photo: json['photo'] as String?,
      messageDate: json['message_date'] as String?,
      mesageTime: json['message_time'] as String?,
      userMessageStatus: json['user_message_status'] as String?,
      messageStar: json['message_star'] as int?,
      messageIsReplay: json['message_is_replay'] as int?,
      messageReplayType: json['message_replay_type'] as String?,
      messageReplayText: json['message_replay_text'] as String?,
      messageReplayAttachmentName: json['message_replay_attachment_name'],
      messageReplayAttachment: json['message_replay_attachment'],
      messageReplayAttachmentThumbnail:
          json['message_replay_attachment_thumbnail'] as String?,
      messageReplayUsername: json['message_replay_username'] as String?,
      messageIsForward: json['message_is_forward'] as int?,
      isDeleted: json['is_deleted'] as int?,
      messageIsBroadcast: json['message_is_broadcast'] as int?,
      pollingId: json['polling_id'],
      pollingQuestion: json['polling_question'],
      pollingAnswerIdData: json['polling_answer_id_data'],
      pollingAnswerData: json['polling_answer_data'],
      pollingCountData: json['polling_count_data'],
      pollingCountDataArr: json['polling_count_data_arr'],
      pollingSubmitAnswerId: json['polling_submit_answer_id'],
      pollingResultData: json['polling_result_data'],
      pollingIsSubmit: json['polling_is_submit'],
      messagePollingAnswerJson: json['message_polling_answer_json'],
      messageIsPinned: json['message_is_pinned'] as bool,
      pollingAnswer: json['polling_answer'] as List<dynamic>,
      pollingVote: json['polling_vote'] as int,
      replayMessage: json['replay_message'],
    );

Map<String, dynamic> _$ChatModelToJson(ChatModel instance) => <String, dynamic>{
      'room_id': instance.roomId,
      'message_id': instance.messageId,
      'message_reaction': instance.messageReaction,
      'from_user_id': instance.fromUserId,
      'from_emp_id': instance.fromEmpId,
      'from_username': instance.fromUsername,
      'from_username_photo': instance.fromUsernamePhoto,
      'to_user_id': instance.toUserId,
      'to_username': instance.toUsername,
      'to_username_photo': instance.toUsernamePhoto,
      'message_type': instance.messageType,
      'message_text': instance.messageText,
      'message_attachment_name': instance.messageAttachmentName,
      'message_attachment': instance.messageAttachment,
      'message_file_duration': instance.messageFileDuration,
      'message_attachment_thumbnail': instance.messageAttachmentThumbnail,
      'message_status': instance.messageStatus,
      'photo': instance.photo,
      'message_date': instance.messageDate,
      'message_time': instance.mesageTime,
      'user_message_status': instance.userMessageStatus,
      'message_star': instance.messageStar,
      'message_is_replay': instance.messageIsReplay,
      'message_replay_type': instance.messageReplayType,
      'message_replay_text': instance.messageReplayText,
      'message_replay_attachment_name': instance.messageReplayAttachmentName,
      'message_replay_attachment': instance.messageReplayAttachment,
      'message_replay_attachment_thumbnail':
          instance.messageReplayAttachmentThumbnail,
      'message_replay_username': instance.messageReplayUsername,
      'message_is_forward': instance.messageIsForward,
      'is_deleted': instance.isDeleted,
      'message_is_broadcast': instance.messageIsBroadcast,
      'polling_id': instance.pollingId,
      'polling_question': instance.pollingQuestion,
      'polling_answer_id_data': instance.pollingAnswerIdData,
      'polling_answer_data': instance.pollingAnswerData,
      'polling_count_data': instance.pollingCountData,
      'polling_count_data_arr': instance.pollingCountDataArr,
      'polling_submit_answer_id': instance.pollingSubmitAnswerId,
      'polling_result_data': instance.pollingResultData,
      'polling_is_submit': instance.pollingIsSubmit,
      'message_polling_answer_json': instance.messagePollingAnswerJson,
      'message_is_pinned': instance.messageIsPinned,
      'polling_answer': instance.pollingAnswer,
      'polling_vote': instance.pollingVote,
      'replay_message': instance.replayMessage,
    };
