// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      messageFileUrl: json['message_file_url'] as String?,
      roomId: json['room_id'] as int?,
      messageId: json['message_id'] as int?,
      message_reaction: json['message_reaction'],
      fromUserId: json['from_user_id'] as int?,
      fromEmpId: json['from_emp_id'] as int?,
      fromUsername: json['from_username'] as String?,
      fromUsernamePhoto: json['from_username_photo'] as String?,
      toUserId: json['to_user_id'] as int?,
      toUsername: json['to_username'] as String?,
      toUsernamePhoto: json['to_username_photo'] as String?,
      messageText: json['message_text'] as String?,
      messageType: json['message_type'] as String?,
      messageAttachmentName: json['message_attachment_name'] as String?,
      messageAttachment: json['message_attachment'] as String?,
      messageAttachmentThumbnail:
          json['message_attachment_thumbnail'] as String?,
      messageFileDuration: json['message_file_duration'] as int?,
      messageStatus: json['message_status'] as String?,
      photo: json['photo'] as String?,
      messageDate: json['message_date'] as String?,
      messageTime: json['message_time'] as String?,
      userMessageStatus: json['user_message_status'] as String?,
      messageStar: json['message_star'] as int?,
      messageIsRelplay: json['message_is_replay'] as int?,
      messageReplayId: json['message_replay_id'] as String?,
      messageReplayType: json['message_replay_type'] as String?,
      messageReplayText: json['message_replay_text'] as String?,
      messageReplayAttachmentName: json['message_replay_attachment_name'],
      messageReplayAttachment: json['message_replay_attachment'],
      messageReplayAttachmentThumbnail:
          json['message_replay_attachment_thumbnail'],
      messageReplayFileDuration: json['message_replay_file_duration'],
      messageReplayUsername: json['message_replay_username'],
      messageisForward: json['message_is_forward'] as int?,
      isDeleted: json['is_deleted'] as int?,
      messageIsBroadcast: json['message_is_broadcast'] as int?,
      messageIsPinned: json['message_is_pinned'] as int?,
      pollingAnswer: json['polling_answer'] as List<dynamic>?,
      pollingVote: json['polling_vote'] as int?,
      pollingIsSubmit: json['polling_is_submit'] as int?,
      replayMessage: json['replay_message'],
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'room_id': instance.roomId,
      'message_id': instance.messageId,
      'message_reaction': instance.message_reaction,
      'from_user_id': instance.fromUserId,
      'from_emp_id': instance.fromEmpId,
      'from_username': instance.fromUsername,
      'from_username_photo': instance.fromUsernamePhoto,
      'to_user_id': instance.toUserId,
      'to_username': instance.toUsername,
      'to_username_photo': instance.toUsernamePhoto,
      'message_text': instance.messageText,
      'message_type': instance.messageType,
      'message_attachment_name': instance.messageAttachmentName,
      'message_attachment': instance.messageAttachment,
      'message_file_url': instance.messageFileUrl,
      'message_attachment_thumbnail': instance.messageAttachmentThumbnail,
      'message_file_duration': instance.messageFileDuration,
      'message_status': instance.messageStatus,
      'photo': instance.photo,
      'message_date': instance.messageDate,
      'message_time': instance.messageTime,
      'user_message_status': instance.userMessageStatus,
      'message_star': instance.messageStar,
      'message_is_replay': instance.messageIsRelplay,
      'message_replay_id': instance.messageReplayId,
      'message_replay_type': instance.messageReplayType,
      'message_replay_text': instance.messageReplayText,
      'message_replay_attachment_name': instance.messageReplayAttachmentName,
      'message_replay_attachment': instance.messageReplayAttachment,
      'message_replay_attachment_thumbnail':
          instance.messageReplayAttachmentThumbnail,
      'message_replay_file_duration': instance.messageReplayFileDuration,
      'message_replay_username': instance.messageReplayUsername,
      'message_is_forward': instance.messageisForward,
      'is_deleted': instance.isDeleted,
      'message_is_broadcast': instance.messageIsBroadcast,
      'message_is_pinned': instance.messageIsPinned,
      'polling_answer': instance.pollingAnswer,
      'polling_vote': instance.pollingVote,
      'polling_is_submit': instance.pollingIsSubmit,
      'replay_message': instance.replayMessage,
    };
